name: Build and Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Build Binary
        run: |
          GOARCH=${{ matrix.arch }} GOOS=linux go build -ldflags "-s -w -X main.Version=${{ github.ref_name }}" -o zt-dns-companion-${{ matrix.arch }} ./cmd/zt-dns-companion

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: zt-dns-companion-${{ matrix.arch }}
          path: zt-dns-companion-${{ matrix.arch }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: zt-dns-companion-amd64

      - name: Download Build Artifacts (ARM64)
        uses: actions/download-artifact@v4
        with:
          name: zt-dns-companion-arm64

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset (AMD64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: zt-dns-companion-amd64
          asset_name: zt-dns-companion-amd64
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (ARM64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: zt-dns-companion-arm64
          asset_name: zt-dns-companion-arm64
          asset_content_type: application/octet-stream